#!/usr/bin/python3

import re
import os
import sys

sys.path.append('../src') 

from timeflies import main

last_arg = sys.argv[-1]
path_prefix, rest = last_arg.split('/', 1)

args = [re.sub(path_prefix + '/', '', x) for x in sys.argv]

print('% autogenerated: ' + ' '.join(sys.argv))
print('\\begin{inputfile}')
print('> timeflies ' + ' '.join(args[1:]))
os.chdir(path_prefix)
main(args)
print('\\end{inputfile}')

exit(0)
