#!/usr/bin/python3

import sys

spc = 'spaces' if sys.argv[1] == '--spc' else ''

print('% autogenerated from: ' + ' '.join(sys.argv))
print('\\begin{inputfile' + spc + '}')
f = open(sys.argv[-1])
for line in f:
    print(line, end='')
f.close()
print('\\end{inputfile' + spc + '}')

exit(0)
