#!/usr/bin/python3

import re
import os
import sys

print('% autogenerated: ' + ' '.join(sys.argv))
print('\\begin{inputfile}')
f = open(sys.argv[1])
for line in f:
    print(line, end='')
f.close()
print('\\end{inputfile}')

exit(0)
